[package]
name        = "data-lib"
description = "Flix data structures."
version     = "0.1.0"
flix        = "0.35.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]


